# Generated by Django 3.0.4 on 2020-03-29 06:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDoList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True)),
                ('created_on', models.DateField(default=datetime.datetime(2020, 3, 29, 6, 33, 46, 661559))),
            ],
            options={
                'verbose_name': 'To Do',
                'verbose_name_plural': 'To Do',
            },
        ),
    ]
