# Generated by Django 3.0.4 on 2020-03-29 06:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='created_on',
            field=models.DateField(default=datetime.datetime(2020, 3, 29, 6, 35, 26, 427825, tzinfo=utc)),
        ),
    ]
