# Generated by Django 3.0.4 on 2020-03-29 06:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20200329_0635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='created_on',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
